
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 06 12:02:33 ART 2020
//----------------------------------------------------

package ar.edu.ub.dc.compilador_micro;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 6;
  public static final int MENOS = 10;
  public static final int P_ABRE = 14;
  public static final int POR = 11;
  public static final int INICIO = 2;
  public static final int DIVIDIDO = 12;
  public static final int FIN = 3;
  public static final int ESCRIBIR = 4;
  public static final int EOF = 0;
  public static final int ASIGN = 5;
  public static final int MAS = 9;
  public static final int NUMERO = 16;
  public static final int ID = 7;
  public static final int MODULO = 13;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 8;
  public static final int P_CIERRA = 15;
}

